global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scheme: https
    metrics_path: /api/metrics
    static_configs:
      - targets: ['fake-news-identifier.onrender.com:443']
